### ISSUE TITLE
Cannot install rubigen 1.5.3

### ISSUE THREAD

**Issue by khelben** [drnic/rubigen#1]
When I try to install rubigen (as a dependency for sdoc_all) it fails as it has a dependency for 'thought-shoulda' which should be now 'shoulda'.

I've tried to change the source code but I'm getting more and more dependency errors.

Do you know how to install this version (1.5.3) of rubigen?

TIA
Christiaan

**Comment by drnic** [comment]
Ok, I think this is fixed now in 1.5.4. Let me know if it's all good.

shoulda etc shouldn't be normal dependencies I think too.

**Comment by khelben** [comment]
Cool, it works! 

I still need to install activesupport 2.3.5 manually, not an issue, I can now install sdoc_all using rvm and ruby1.9.

Thanks for the swift response.

Christiaan

**Comment by drnic** [comment]
How come you had to install activesupport manually? gem install rubigen didn't do it?

**Comment by khelben** [comment]
no, it complained about it but didn't install it.
please note that I've already installed rails 3 beta in this gemset

**Comment by drnic** [comment]
It should require the explicit activesupport:

extra_deps << ['activesupport','2.3.5']

Can I have a stdout of the error on install?

**Comment by khelben** [comment]
I cannot seem to reproduce it, perhaps some mistake on my side.

Thanks anyway for the swift reponse.
