### ISSUE TITLE
rails 3 compatibility

### ISSUE THREAD

**Issue by renemendoza** [drnic/rubigen#3]
activesupport ~> 2.3.5 requirement makes impossible to load activesupport 3

files affected bin/rubigen and lib/rubigen.rb

kudos

**Comment by drnic** [comment]
Agreed; rubigen would benefit from activesupport 3 and only having to load the bits and pieces that are required instead of all of it.

**Comment by bklang** [comment]
Fixed in Rubigen 1.5.6
